version: '3.8'
services:
  app:
    build:
      context: .
      target: dev
    command: air
    ports:
      - '8080:8080'
  postgresql_db:
    image: postgres:14.1-alpine
    restart: always
    container_name: postgres_db
    environment:
      - POSTGRES_USER=odmin
      - POSTGRES_PASSWORD=odmin
      - POSTGRESS_DB=odmin
    ports:
      - '5432:5432'
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
      - ./postgresql:/var/lib/postgresql/data
volumes:
  db:
    driver: local
