version: '3.8'
services:
  postgresql_db:
    image: postgres:14.1-alpine
    restart: always
    container_name: postgres_db
    environment:
      - POSTGRES_USER=odmin
      - POSTGRES_PASSWORD=odmin
    ports:
      - '5432:5432'
    volumes:
      - ./postgresql:/var/lib/postgresql/data
volumes:
  db:
    driver: local
